# -*- coding: utf-8 -*-
"""harsha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V84Tj6U7WpaWN10uqnFiBmSd11bOpCqu

# QUESTION 1, TAKING INPUT AND IF THE STRING IS GREATER THAN 2 ALPHABETS THEN DELETING THE 2 CHARACTERS AND PRINTING THE REVERSE OF IT
"""

str=list(input())

if len(str)>2:
  del str[:2]
  rev_str=str[::-1]
  print(rev_str)

final_str = ''.join(rev_str)
print(final_str)

"""# QUESTION-1B, ARITHEMATIC OPERATIONS"""

a=int(input())
b=int(input())

print("sum of two no is", a+b)
print("subtraction of two no is", a-b)
print("multiplication of two no is", a*b)
print("division of two no is", a/b)

"""# QUESTION 2

"""

sentence = input("Enter a sentence: ")

mod_sen = sentence.replace('python', 'pythons')

print("Updated:", mod_sen)

"""# Question 3

"""

grade= int(input())
if grade>=90:
  print('A')
elif  grade >= 80 and grade < 90:
  print('B')
elif  grade >= 70 and grade < 80:
  print('C')
elif  grade >= 60 and grade < 70:
  print('D')
else:
  print('FAIL')

